path: 
train:
val:

#classes
names:
  0: ceiling_mounted_luminaire
  1: wall_mounted_luminaire
  2: lightingstandard
  3: self_powered_exit_sign
  4: emergency_battery_unit
  5: emergency_remote_head
  6: single_pole_light_switch
  7: key_operated_switch
  8: three_way_light_switch
  9: occupancy_sensor_manual_override_light_switch
  10: dimmer_switch
  11: suite_master_switch
  12: fan_switch
  13: ceiling_occupancy_switch
  14: 15A_Duplex_Receptacle
  15: 15A_Duplex_Receptacle_Mounted
  16: T_Slot_Receptacle
  17: Interrupter_Receptacle
  18: Split_Type_Receptacle
  19: Ground_Fault_Receptacle
  20: Duplex_Split_Type_Receptacle
  21: Floor_Mounted_Box
  22: 20A_Duplex_Ground_Fault_Receptacle
  23: 20A_Duplex_Receptacle
  24: 20A_Quadplex_Receptacle
  25: 15A_125V_Receptacle
  26: 20A_Receptacle
  27: 30A_Receptacle
  28: 50A_Receptacle
  29: Wall_Mounted_Panel_Board
  30: Unfused_Disconnect_Switch
  31: Disconnect_Switch
  32: Motor_Starter_SF1
  33: Transformer_As_Noted
  34: Electric_Heater
  35: Line_Voltage_Thermostat
  36: OBC_Push_Button
  37: Direct_Power_Connection_To_Equipment
  38: Provide_Power_Connection_To_Motor
  39: Fire_Alarm_Adressable_Module
  40: FIre_Alarm_Isolator
  41: Fire_Alarm_Manual_Pull_Station
  42: Fire_Alarm_Heat_Detector_Ceiling_Mounted
  43: Fire_Alarm_Heat_Detector_Fixed
  44: Fire_Alarm_Smoke_Detector_Ceiling_Mounted
  45: Fire_Alarm_Smoke_Combination_Detector
  46: Fire_Alarm_Co_Detector
  47: Fire_Alarm_Duct_Type_Smoke_Detector
  48: Fire_Alarm_Strobe
  49: 125V_Smoke_Alarm
  50: Fire_Alarm_Trouble_Light
  51: Fire_Alarm_Handset
  52: Fire_Alarm_Speaker_Strobe
  53: Fire_Alarm_Speaker
  54: Wireles_Door_Button
  55: Wireless_Strobe_Chime
  56: Telephone_Wall_Outlet
  57: Data_Wall_Outlet
  58: Wireless_Access_Points
  59: TV_Wall_Outlet
  60: CCTCV_Camera
  61: SecurityDoor_Contact
  62: Security_Electric_Strike
  63: Junction_Box
  64: Doorbell_System
  65: Intercom
  66: CardReader
  67: Speakers
  68: GroundBus
  69: GroundRod
  70: fire_alarm_horn
  71: fire_alarm_strobe_horn
